@echo off
chcp 65001 >nul
title 肥鱼启动器 v1.2.2 ^| FatFish Launcher v1.2.2 ^| 肥魚起動器 v1.2.2 ^| 팻피시 기동기 v1.2.2
cd /d "%~dp0"

REM ============================================================
REM  0) [GUI-FIRST v1] 先把自己搬进「传统控制台窗口」
REM
REM  为什么要有这一步：
REM     Windows 11 的「默认终端应用程序」可能是 Windows 终端，
REM     那时本窗口是 ConPTY —— GetConsoleWindow() 给回的是
REM     PseudoConsoleWindow（终端宿主的内部伪窗口），**主程序没法把
REM     它藏掉**，「启动后只剩一块对话窗口」就做不到。
REM
REM     实测（本机）：
REM       CREATE_NEW_CONSOLE / 默认宿主 → 'PseudoConsoleWindow'  不可隐藏
REM       conhost.exe 显式启动          → 'ConsoleWindowClass'   可隐藏 ✓
REM     所以这里先让 conhost.exe 把自己重新拉起来，换到传统控制台窗口里
REM     再往下走。一次即可（靠 FISH_CONHOST 防循环）。
REM
REM  不要这个行为：启动前 set FATFISH_NO_CONHOST=1
REM ============================================================
if not defined FATFISH_NO_CONHOST if not defined FISH_CONHOST if exist "%SystemRoot%\System32\conhost.exe" (
    set "FISH_CONHOST=1"
    start "" "%SystemRoot%\System32\conhost.exe" cmd /k "%~f0"
    exit
)

REM ============================================================
REM  1) 检查 Python
REM ============================================================
where python >nul 2>nul
if errorlevel 1 (
    echo [错误] 未检测到 python 命令，请先安装 Python 并加入 PATH ^| [Error] python command not found. Please install Python and add it to PATH ^| [誤謬] python 命令を検出できません。Python を設置し PATH に追加してください ^| [오류] python 명령을 검출할 수 없습니다. Python을 설치하고 PATH에 추가하십시오
    pause
    exit /b 1
)

REM ============================================================
REM  2) 激活虚拟环境（如果存在）
REM ============================================================
if exist "venv\Scripts\activate.bat" (
    call "venv\Scripts\activate.bat"
    echo [情報] 仮想環境 venv を有効化 ^| [信息] 已激活虚拟环境 venv ^| [Info] Virtualenv venv activated ^| [정보] 가상환경 venv를 활성화함
) else if exist ".venv\Scripts\activate.bat" (
    call ".venv\Scripts\activate.bat"
    echo [情報] 仮想環境 .venv を有効化 ^| [信息] 已激活虚拟环境 .venv ^| [Info] Virtualenv .venv activated ^| [정보] 가상환경 .venv를 활성화함
) else (
    echo [情報] 仮想環境なし、全局 Python を使用 ^| [信息] 未发现虚拟环境，使用全局 Python ^| [Info] No virtualenv found, using global Python ^| [정보] 가상환경 없음, 전역 Python을 사용
)

REM ============================================================
REM  3) 检查依赖，缺则自动安装
REM ============================================================
python -c "import openai, dotenv, requests" >nul 2>nul
if errorlevel 1 (
    echo [提示] 缺少依赖，正在安装... ^| [Info] Missing dependencies, installing... ^| [情報] 依存関係が不足、設置中... ^| [정보] 의존관계가 부족, 설치 중...
    python -m pip install --upgrade pip
    python -m pip install openai python-dotenv requests
    if errorlevel 1 (
        echo [错误] 依赖安装失败，请手动执行： ^| [Error] Dependency install failed, please run manually: ^| [誤謬] 依存関係の設置に失敗しました。手動で実行してください： ^| [오류] 의존관계 설치 실패, 수동으로 실행하십시오:
        echo        python -m pip install openai python-dotenv requests
        pause
        exit /b 1
    )
    echo [信息] 依赖安装完成 ^| [Info] Dependencies installed ^| [情報] 依存関係の設置完了 ^| [정보] 의존관계 설치 완료
) else (
    echo [信息] 依赖检查通过 ^| [Info] Dependency check passed ^| [情報] 依存関係チェック合格 ^| [정보] 의존관계 검사 통과
)

REM ============================================================
REM  4) 检查 .env —— 不存在则自动生成一份符合要求的模板
REM ============================================================
if not exist ".env" (
    echo.
    echo [提示] 未找到 .env，正在自动生成模板... ^| [Info] .env not found, generating a template... ^| [情報] .env が見つかりません。テンプレートを自動生成します... ^| [정보] .env를 찾을 수 없습니다. 템플릿을 자동 생성합니다...
    (
        echo # ============================================================
        echo #  FatFish 环境配置 [FatFish environment config]
        echo #  由启动器自动生成 [auto-generated by the launcher]
        echo #  请把下面的占位符替换为你自己的真实 key [replace placeholders with your real keys]
        echo # ============================================================
        echo.
        echo # DeepSeek 大模型 API Key（必填）[required]
        echo DEEPSEEK_API_KEY=sk-你的DeepSeekKey
        echo.
        echo # Tavily 联网搜索 API Key（可选，联网搜索用）[optional, for web search]
        echo TAVILY_API_KEY=tvly-你的TavilyKey
        echo.
    ) > ".env"
    echo [信息] 已生成 .env 模板 ^| [Info] .env template created ^| [情報] .env テンプレートを生成しました ^| [정보] .env 템플릿을 생성했습니다
    echo        请编辑 .env 填入真实 key 后再使用联网/对话功能 ^|        Please edit .env and fill in real keys before use
    echo.
)

REM ============================================================
REM  5) 启动（在独立的新命令提示符窗口里运行主程序）
REM     主程序窗口独立运行：主程序结束后不自动关闭，需按键退出。
REM     本启动器不监听、不干预子窗口。
REM
REM     注意：这里用 cmd /k ""..."" 的双引号包裹法。
REM     start 的第一个引号参数是【窗口标题】，其后才是要执行的命令；
REM     若命令内部再含引号（如 call "路径"），必须用额外的外层引号
REM     把整条命令括起来，否则含空格的路径会被截断 → 新窗口闪退。
REM ============================================================
REM ============================================================
REM  5) 启动（[GUI-FIRST v1] 就**在本窗口**里跑）
REM
REM  旧做法： start "" cmd /k "fatfish_runtime.bat"
REM           → 另开一个 runtime 控制台窗口（再加监控器 + 状态台 = 一堆窗口）
REM  新做法： call "fatfish_runtime.bat" —— 同一个窗口往下跑；主程序起来后
REM           会把本控制台窗口藏起来，界面上只剩一块对话窗口。
REM  需要旧的多窗口形态：启动前 set FATFISH_MULTIWIN=1
REM ============================================================
echo.
echo 🐟 正在启动肥鱼 v1.2.2... ^| Starting FatFish v1.2.2... ^| 肥魚 v1.2.2 を起動中... ^| 팻피시 v1.2.2 기동 중...
echo.
echo    单窗口模式：界面上只会出现一块对话窗口 [single-window mode]
echo    本控制台随后会自动隐藏（在窗口里敲 /console on 可唤回）
echo    [this console will be hidden; type /console on to bring it back]
echo.

call "%~dp0fatfish_runtime.bat"

REM ============================================================
REM  6) 收尾
REM     [GUI-FIRST v1] 同窗口运行，这里不再 pause：
REM       · 用户主动退出 → runtime.bat 里的 exit 已把窗口一起关掉；
REM       · 其它情况     → runtime.bat 自己会 pause 等按键。
REM ============================================================
exit /b %errorlevel%
