@echo off
chcp 65001 >nul
title 肥鱼启动器 v1.0.4 ^| FatFish Launcher v1.0.4 ^| 肥魚起動器 v1.0.4 ^| 팻피시 기동기 v1.0.4
cd /d "%~dp0"

REM ============================================================
REM  1) 检查 Python
REM ============================================================
where python >nul 2>nul
if errorlevel 1 (
    echo [错误] 未检测到 python 命令，请先安装 Python 并加入 PATH ^| [Error] python command not found. Please install Python and add it to PATH ^| [誤謬] python 命令を検出できません。Python を設置し PATH に追加してください ^| [오류] python 명령을 검출할 수 없습니다. Python을 설치하고 PATH에 추가하십시오
    pause
    exit /b 1
)

REM ============================================================
REM  2) 激活虚拟环境（如果存在）
REM ============================================================
if exist "venv\Scripts\activate.bat" (
    call "venv\Scripts\activate.bat"
    echo [情報] 仮想環境 venv を有効化 ^| [信息] 已激活虚拟环境 venv ^| [Info] Virtualenv venv activated ^| [정보] 가상환경 venv를 활성화함
) else if exist ".venv\Scripts\activate.bat" (
    call ".venv\Scripts\activate.bat"
    echo [情報] 仮想環境 .venv を有効化 ^| [信息] 已激活虚拟环境 .venv ^| [Info] Virtualenv .venv activated ^| [정보] 가상환경 .venv를 활성화함
) else (
    echo [情報] 仮想環境なし、全局 Python を使用 ^| [信息] 未发现虚拟环境，使用全局 Python ^| [Info] No virtualenv found, using global Python ^| [정보] 가상환경 없음, 전역 Python을 사용
)

REM ============================================================
REM  3) 检查依赖，缺则自动安装
REM ============================================================
python -c "import openai, dotenv, requests" >nul 2>nul
if errorlevel 1 (
    echo [提示] 缺少依赖，正在安装... ^| [Info] Missing dependencies, installing... ^| [情報] 依存関係が不足、設置中... ^| [정보] 의존관계가 부족, 설치 중...
    python -m pip install --upgrade pip
    python -m pip install openai python-dotenv requests
    if errorlevel 1 (
        echo [错误] 依赖安装失败，请手动执行： ^| [Error] Dependency install failed, please run manually: ^| [誤謬] 依存関係の設置に失敗しました。手動で実行してください： ^| [오류] 의존관계 설치 실패, 수동으로 실행하십시오:
        echo        python -m pip install openai python-dotenv requests
        pause
        exit /b 1
    )
    echo [信息] 依赖安装完成 ^| [Info] Dependencies installed ^| [情報] 依存関係の設置完了 ^| [정보] 의존관계 설치 완료
) else (
    echo [信息] 依赖检查通过 ^| [Info] Dependency check passed ^| [情報] 依存関係チェック合格 ^| [정보] 의존관계 검사 통과
)

REM ============================================================
REM  4) 检查 .env —— 不存在则自动生成一份符合要求的模板
REM ============================================================
if not exist ".env" (
    echo.
    echo [提示] 未找到 .env，正在自动生成模板... ^| [Info] .env not found, generating a template... ^| [情報] .env が見つかりません。テンプレートを自動生成します... ^| [정보] .env를 찾을 수 없습니다. 템플릿을 자동 생성합니다...
    (
        echo # ============================================================
        echo #  FatFish 环境配置 [FatFish environment config]
        echo #  由启动器自动生成 [auto-generated by the launcher]
        echo #  请把下面的占位符替换为你自己的真实 key [replace placeholders with your real keys]
        echo # ============================================================
        echo.
        echo # DeepSeek 大模型 API Key（必填）[required]
        echo DEEPSEEK_API_KEY=sk-你的DeepSeekKey
        echo.
        echo # Tavily 联网搜索 API Key（可选，联网搜索用）[optional, for web search]
        echo TAVILY_API_KEY=tvly-你的TavilyKey
        echo.
    ) > ".env"
    echo [信息] 已生成 .env 模板 ^| [Info] .env template created ^| [情報] .env テンプレートを生成しました ^| [정보] .env 템플릿을 생성했습니다
    echo        请编辑 .env 填入真实 key 后再使用联网/对话功能 ^|        Please edit .env and fill in real keys before use
    echo.
)

REM ============================================================
REM  5) 启动（在独立的新命令提示符窗口里运行主程序）
REM     主程序窗口独立运行：主程序结束后不自动关闭，需按键退出。
REM     本启动器不监听、不干预子窗口。
REM
REM     注意：这里用 cmd /k ""..."" 的双引号包裹法。
REM     start 的第一个引号参数是【窗口标题】，其后才是要执行的命令；
REM     若命令内部再含引号（如 call "路径"），必须用额外的外层引号
REM     把整条命令括起来，否则含空格的路径会被截断 → 新窗口闪退。
REM ============================================================
set "FISHWIN=FatFish Runtime v1.0.4"

echo.
echo 🐟 正在新窗口中启动肥鱼 v1.0.4... ^| Starting FatFish v1.0.4 in a new window... ^| 新しいウィンドウで肥魚 v1.0.4 を起動中... ^| 새 창에서 팻피시 v1.0.4 기동 중...
echo    主程序运行窗口标题 [runtime window title]：%FISHWIN%
echo    主程序窗口独立运行：结束后需按任意键才关闭 [runtime window is standalone: press any key to close after it ends]
echo.

REM Launch the main program in a standalone window
REM Best practice: start "" cmd /k "path" -- the first "" is the window title placeholder,
REM wrap the path in its own pair of quotes and do not nest quotes or && inside the command,
REM this way a path with spaces will not be truncated and the new window will not flash-close.
start "" cmd /k "%~dp0fatfish_runtime.bat"

REM ============================================================
REM  6) 启动器收尾
REM     默认：启动器窗口保留，方便你看输出；按任意键再关。
REM     若想启动完就自动关，把下面的 pause 删掉、保留 exit 即可。
REM ============================================================
echo [完成] 主程序已在新窗口启动 ^| [Done] Runtime launched in the new window.
echo 按任意键关闭本启动器窗口 [press any key to close this launcher window]...
pause >nul
exit
