@echo off
chcp 65001 >nul
title FatFish Launcher v1.1.1
cd /d "%~dp0"

REM ============================================================
REM  1) Check Python
REM ============================================================
where python >nul 2>nul
if errorlevel 1 (
    echo [Error] python command not found. Please install Python and add it to PATH.
    pause
    exit /b 1
)

REM ============================================================
REM  2) Activate a virtualenv if one exists
REM ============================================================
if exist "venv\Scripts\activate.bat" (
    call "venv\Scripts\activate.bat"
    echo [Info] Virtualenv venv activated
) else if exist ".venv\Scripts\activate.bat" (
    call ".venv\Scripts\activate.bat"
    echo [Info] Virtualenv .venv activated
) else (
    echo [Info] No virtualenv found, using global Python
)

REM ============================================================
REM  3) Check dependencies, install automatically if missing
REM ============================================================
python -c "import openai, dotenv, requests" >nul 2>nul
if errorlevel 1 (
    echo [Info] Missing dependencies, installing...
    python -m pip install --upgrade pip
    python -m pip install openai python-dotenv requests
    if errorlevel 1 (
        echo [Error] Dependency install failed, please run manually:
        echo        python -m pip install openai python-dotenv requests
        pause
        exit /b 1
    )
    echo [Info] Dependencies installed
) else (
    echo [Info] Dependency check passed
)

REM ============================================================
REM  4) Check .env -- generate a compliant template if missing
REM ============================================================
if not exist ".env" (
    echo.
    echo [Info] .env not found, generating a template...
    (
        echo # ============================================================
        echo #  FatFish environment config
        echo #  auto-generated by the launcher
        echo #  replace the placeholders with your real keys
        echo #  rule: never place a trailing comment on an EMPTY value line
        echo # ============================================================
        echo.
        echo # Main model API key (required)
        echo FATFISH_API_KEY=
        echo FATFISH_BASE_URL=https://api.deepseek.com
        echo FATFISH_MODEL=deepseek-flash
        echo.
        echo # Web search API key (optional, for web search)
        echo TAVILY_API_KEY=
        echo.
    ) > ".env"
    echo [Info] .env template created
    echo        Please edit .env and fill in real keys before use.
    echo.
)

REM ============================================================
REM  5) Launch the main program in a standalone new console window
REM     The runtime window is standalone: it does not close itself when the
REM     program ends; press any key to exit.
REM     This launcher neither monitors nor interferes with the child window.
REM
REM     Note: we use the cmd /k ""..."" double-quote wrapping here.
REM     start's first quoted argument is the WINDOW TITLE; the command comes after.
REM     If the command itself contains quotes (e.g. call "path"), an extra outer
REM     pair is required, otherwise a path with spaces gets truncated and the new
REM     window flash-closes.
REM ============================================================
set "FISHWIN=FatFish Runtime v1.1.1"

echo.
echo Starting FatFish v1.1.1 in a new window...
echo    Runtime window title: %FISHWIN%
echo    The runtime window is standalone: press any key to close after it ends.
echo.

REM Launch the main program in a standalone window
REM Best practice: start "" cmd /k "path" -- the first "" is the window title
REM placeholder; wrap the path in its own pair of quotes and do not nest quotes
REM or && inside the command, so a path with spaces is not truncated and the new
REM window will not flash-close.
start "" cmd /k "%~dp0fatfish_runtime.bat"

REM ============================================================
REM  6) Launcher wrap-up
REM     Default: keep this launcher window open so you can read the output;
REM     press any key to close. To auto-close after launch, delete the pause
REM     below and keep exit.
REM ============================================================
echo [Done] Runtime launched in the new window.
echo Press any key to close this launcher window...
pause >nul
exit
